[package]
name = "pitch"
version = "0.0.0"
authors = ["Leon Tan <leon.arian.tan@gmail.com>"]
edition = "2018"

[dependencies]
num-complex = "0.3.1"

[dev-dependencies]
soundio = "0.2.1"
rand = "0.7.3"

